# Generated by Django 5.2.16 on 2026-07-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='status_saida',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='total_com_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='total_sem_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
