# Generated by Django 5.2.16 on 2026-08-15 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_modo_valor_gasto'),
        ('estoque', '0002_produto_status_saida_produto_total_com_desconto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='clientes.cliente', verbose_name='Cliente'),
        ),
    ]
