# Generated by Django 5.2.16 on 2026-08-18 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_produto_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
