# Generated by Django 5.2.16 on 2026-10-09 00:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoAssistenteIA',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resposta_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('pergunta', models.TextField(blank=True, default='')),
                ('resposta', models.TextField(blank=True, default='')),
                ('avaliacao', models.CharField(choices=[('positiva', 'Positiva'), ('negativa', 'Negativa')], max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_assistente_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação do Assistente IA',
                'verbose_name_plural': 'Avaliações do Assistente IA',
                'ordering': ['-criada_em'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'resposta_id'), name='unique_avaliacao_usuario_resposta')],
            },
        ),
    ]
