# Generated by Django 5.2.16 on 2026-09-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
