# Generated by Django 5.2.16 on 2026-09-19 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_saidaproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidaproduto',
            name='data_saida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
