# Generated by Django 5.2.16 on 2026-08-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
