# Generated by Django 5.2.16 on 2026-08-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfilusuario_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='status_conexao',
            field=models.CharField(choices=[('online', 'Online'), ('ausente', 'Ausente'), ('offline', 'Offline')], default='online', max_length=20),
        ),
    ]
