# Generated by Django 5.2.16 on 2026-08-20 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_perfilusuario_status_conexao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='senha_visivel',
        ),
    ]
