# Generated by Django 5.2.16 on 2026-09-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_perfilusuario_senha_visivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='data_inatividade',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
