# Generated by Django 5.2.16 on 2026-09-03 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('saida', 'Gerar Saída'), ('cadastro', 'Novo Usuário'), ('edicao', 'Edição de Dados'), ('perfil', 'Alteração de Perfil')], default='saida', max_length=50)),
                ('descricao', models.TextField()),
                ('nome_usuario_afetado', models.CharField(blank=True, max_length=150)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario_afetado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_afetados', to=settings.AUTH_USER_MODEL)),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_gerados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
