# Generated by Django 5.2.16 on 2026-08-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cnh', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria_cnh', models.CharField(blank=True, max_length=10, null=True)),
                ('emissao_cnh', models.DateField(blank=True, null=True)),
                ('vencimento_cnh', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(default='Ativo', max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('valor_gasto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ultima_compra', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
