# Generated by Django 5.2.16 on 2026-08-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('fisico', 'Pessoa Física'), ('juridico', 'Pessoa Jurídica')], default='fisico', max_length=10),
        ),
    ]
