# Generated by Django 5.2.16 on 2026-08-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_inclusao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Inclusão'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
    ]
