# Generated by Django 5.2.16 on 2026-08-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_data_inclusao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='modo_valor_gasto',
            field=models.CharField(default='Automático (somar produtos)', max_length=50, verbose_name='Modo Valor Gasto'),
        ),
    ]
