# Generated by Django 5.2.16 on 2026-08-15 19:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_modo_valor_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ultima_compra',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Compra'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor_gasto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Gasto Total'),
        ),
    ]
