# Generated by Django 5.2.16 on 2026-10-05 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_clientehistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientehistorico',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientehistorico',
            name='tipo_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientehistorico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico', to='clientes.cliente'),
        ),
    ]
